### ISSUE TITLE
Why is this package needed?

### ISSUE THREAD

**Issue by stefanoborini** [wildland-creative/pyhere#8]
You can always get the path of the current script with ``__file__``
```
$ python bar.py 
/Users/myuser/tmp/foo/bar.py
$ cd ..
$ python foo/bar.py 
/Users/myuser/tmp/foo/bar.py
$ more foo/bar.py 
import os
print(os.path.abspath(__file__))
```

**Comment by joshpsawyer** [comment]
this package is not for getting the path of the current script - it allows you to define a `.here` file somewhere higher in the project directory, and then specify paths relative to that. if the python file is then moved to another subfolder, the code will still work. it's more for large projects with a variety of scripts all acting on the same data set. as it replicates R functionality, you can also read their justification.

https://here.r-lib.org/

**Comment by stefanoborini** [comment]
I have never needed such package in 20 years of python programming. If the project is large, one uses pkg_resources.

**Comment by JohnGoertz** [comment]
This package is super helpful when working in notebooks as part of a larger project. I often need to define standardized, relative paths that are easy to use for every contributor and are portable between notebooks and repo clones.
